### ISSUE TITLE
ARC Semantic Issue

### ISSUE THREAD

**Issue by LuisRodriguezLD** [fusetools/Fuse.RMStore#2]
Found a bug, in Fuse 0.35 I get the following errors on Xcode

<img width="486" alt="screen shot 2017-03-17 at 8 22 38 am" src="https://cloud.githubusercontent.com/assets/16706463/24044827/e9ba4434-0aea-11e7-9ed8-fac3a34c809d.png">

In Fuse 0.34 everything works good

**Comment by cbaggers** [comment]
Should be fixed on master now. Please let me know how it goes. My limited tests look good so I'll close this if it works for you folks

**Comment by eksperts** [comment]
Looking good on my machine

**Comment by cbaggers** [comment]
rock on! thanks for the help
